### ISSUE TITLE
反射失败

### ISSUE THREAD

**Issue by olHlo** [Jesse505/AwesomeLog#1]
W/esse.awesomelo: Accessing hidden method Lsun/nio/ch/FileChannelImpl;->unmap(Ljava/nio/MappedByteBuffer;)V (blacklist, reflection, denied)
W/System.err: java.lang.NoSuchMethodException: sun.nio.ch.FileChannelImpl.unmap [class java.nio.MappedByteBuffer]
        at java.lang.Class.getMethod(Class.java:2072)
        at java.lang.Class.getDeclaredMethod(Class.java:2050)
        at com.android.jesse.log.io.LightLog.unmap(LightLog.java:288)
        at com.android.jesse.log.io.LightLog.flush(LightLog.java:106)
        at com.android.jesse.log.io.LightLog.flush(LightLog.java:65)
        at com.android.jesse.log.stragety.DiskDailyLogStrategy.flush(DiskDailyLogStrategy.java:71)
        at com.android.jesse.log.stragety.CsvFormatStrategy.flush(CsvFormatStrategy.java:71)
        at com.android.jesse.log.Printer.DiskLogPrinter.flush(DiskLogPrinter.java:53)
        at com.android.jesse.log.logger.ALogger.flush(ALogger.java:150)
        at com.android.jesse.log.ALog.flush(ALog.java:129)
        at com.android.jesse.awesomelog.MainActivity.flush(MainActivity.java:58)
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385)
        at android.view.View.performClick(View.java:7213)
        at android.view.View.performClickInternal(View.java:7187)
        at android.view.View.access$3500(View.java:828)
W/System.err:     at android.view.View$PerformClick.run(View.java:27675)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8341)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
W/esse.awesomelo: Accessing hidden method Lsun/nio/ch/FileChannelImpl;->unmap(Ljava/nio/MappedByteBuffer;)V (blacklist, reflection, denied)
W/System.err: java.lang.NoSuchMethodException: sun.nio.ch.FileChannelImpl.unmap [class java.nio.MappedByteBuffer]
        at java.lang.Class.getMethod(Class.java:2072)
        at java.lang.Class.getDeclaredMethod(Class.java:2050)
        at com.android.jesse.log.io.LightLog.unmap(LightLog.java:288)
        at com.android.jesse.log.io.LightLog.flush(LightLog.java:107)
        at com.android.jesse.log.io.LightLog.flush(LightLog.java:65)
        at com.android.jesse.log.stragety.DiskDailyLogStrategy.flush(DiskDailyLogStrategy.java:71)
        at com.android.jesse.log.stragety.CsvFormatStrategy.flush(CsvFormatStrategy.java:71)
        at com.android.jesse.log.Printer.DiskLogPrinter.flush(DiskLogPrinter.java:53)
        at com.android.jesse.log.logger.ALogger.flush(ALogger.java:150)
        at com.android.jesse.log.ALog.flush(ALog.java:129)
        at com.android.jesse.awesomelog.MainActivity.flush(MainActivity.java:58)
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385)
        at android.view.View.performClick(View.java:7213)
        at android.view.View.performClickInternal(View.java:7187)
        at android.view.View.access$3500(View.java:828)
        at android.view.View$PerformClick.run(View.java:27675)
        at android.os.Handler.handleCallback(Handler.java:900)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8341)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
W/esse.awesomelo: Accessing hidden method Lsun/nio/ch/FileChannelImpl;->unmap(Ljava/nio/MappedByteBuffer;)V (blacklist, reflection, denied)
W/System.err: java.lang.NoSuchMethodException: sun.nio.ch.FileChannelImpl.unmap [class java.nio.MappedByteBuffer]
        at java.lang.Class.getMethod(Class.java:2072)
        at java.lang.Class.getDeclaredMethod(Class.java:2050)
        at com.android.jesse.log.io.LightLog.unmap(LightLog.java:288)
        at com.android.jesse.log.io.LightLog.flush(LightLog.java:113)
        at com.android.jesse.log.io.LightLog.flush(LightLog.java:65)
        at com.android.jesse.log.stragety.DiskDailyLogStrategy.flush(DiskDailyLogStrategy.java:71)
        at com.android.jesse.log.stragety.CsvFormatStrategy.flush(CsvFormatStrategy.java:71)
        at com.android.jesse.log.Printer.DiskLogPrinter.flush(DiskLogPrinter.java:53)
        at com.android.jesse.log.logger.ALogger.flush(ALogger.java:150)
        at com.android.jesse.log.ALog.flush(ALog.java:129)
        at com.android.jesse.awesomelog.MainActivity.flush(MainActivity.java:58)
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385)
        at android.view.View.performClick(View.java:7213)
        at android.view.View.performClickInternal(View.java:7187)
        at android.view.View.access$3500(View.java:828)
        at android.view.View$PerformClick.run(View.java:27675)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8341)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)

**Comment by Jesse505** [comment]
9.0 以上对反射做了限制，你是9.0以上的系统吧

**Comment by Jesse505** [comment]
绕过9.0反射限制，已测试。
